sfdx force source retrieve -m layout:"Clan__c-Clan Layout"
sfdx force source retrieve -m layout:"ClanCapital__c-Clan Capital Layout"
sfdx force source retrieve -m layout:"ClanLabel__c-Clan Label Layout"
sfdx force source retrieve -m layout:"ClanLocation__c-Clan Location Layout"
sfdx force source retrieve -m layout:"ClanMember__c-Clan Member Layout"
sfdx force source retrieve -m layout:"ClanMemberHistory__c-Clan Member History Layout"
sfdx force source retrieve -m layout:"ClanToSync__c-Clan to Sync Layout"
sfdx force source retrieve -m layout:"ClanWar__c-Clan War Layout"
sfdx force source retrieve -m layout:"ClanWarAttack__c-Clan War Attack Layout"
sfdx force source retrieve -m layout:"ClanWarLeagueClan__c-Clan War League Clan Layout"
sfdx force source retrieve -m layout:"ClanWarLeagueClanMember__c-Clan War League Clan Member Layout"
sfdx force source retrieve -m layout:"ClanWarLeagueGroup__c-Clan War League Group Layout"
sfdx force source retrieve -m layout:"ClanWarLeagueRound__c-Clan War League Round Layout"
sfdx force source retrieve -m layout:"ClanWarLeagueRoundWar__c-Clan War League Round War Layout"
sfdx force source retrieve -m layout:"ClanWarMember__c-Clan War Member Layout"
sfdx force source retrieve -m layout:"WarClan__c-War Clan Layout"